plugins:
  bandit:
    enabled: true
  fixme:
    enabled: true
  config:
    strings:
      - FIXME
      - BUG
      - CHECK
      - TODO
      - FIX
      - CHANGE
  git-legal:
    enabled: true
  markdownlint:
    enabled: true
    checks:
      MD013:
        enabled: false
      MD033:
        enabled: false
  pylint:
    enabled: true
  radon: 
    enabled: true
    config: 
      python_version: 3
  sonar-python:
    enabled: true  
    config:
      tests_patterns:
        - eventol/manager/tests/**
        - eventol/eventol/tests/**

exclude_patterns:
  - ".github/"
  - "deploy/"
  - "docs/"
  - "eventol/conf/"
  - "eventol/manager/media/"
  - "eventol/manager/migrations/"
  - "eventol/manager/static/"
  - "eventol/manager/templates/"
  - "db.*"
  - "**/test_*.py"
