esversion: 6

jshint:
  enabled: false

python:
  enabled: true
  config_file: .pylintrc

prettier:
  enabled: true
  config_file: eventol/front/.prettierrc

eslint:
  enabled: true
  config_file: eventol/front/.eslintrc.json

javascript:
  enable: true
  esversion: 6
  config_file: eventol/front/.eslintrc.json

scss:
  enabled: true
  config_file: eventol/front/.sass-lint.yml


