repos:
 # Codespell for common misspellings
 - repo: https://github.com/codespell-project/codespell
   rev: v2.3.0
   hooks:
     - id: codespell
       name: Spell Checker (backend and frontend)
       files: ^(eventol|manager)/ # Only backend and frontend directories
       exclude: |
                (?x)(
                ^eventol/manager/static/|
                ^eventol/static/|
                ^eventol/conf/locale|
                ^eventol/manager/template
                )
       stages: [pre-commit]
 # Ruff for Python formatting and linting
 - repo: https://github.com/astral-sh/ruff-pre-commit
   rev: v0.7.0
   hooks:
     - id: ruff
       name: Ruff Linter (backend)
       args: ["--fix"] # Automatically fix issues
       files:  ^(eventol|manager) # Only backend folder
       stages: [pre-commit]
     - id: ruff-format
       name: Ruff Formatter (backend)
       files: ^(eventol|manager) # Only backend folder
       stages: [pre-commit]

 