version: '3.4'

services:
  worker:
    build:
      context: ../../.
    volumes:
      - type: bind
        source: ../../
        target: /usr/src/app
    environment:
      - DJANGO_CONFIGURATION=Dev
      - PSQL_HOST=postgres
    ports:
      - '8000:8000'
    depends_on:
      - redis
      - postgres

  redis:
    image: redis:4.0.2

  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=eventol
      - POSTGRES_DB=eventol
    ports:
      - '5432:5432'
    volumes:
      - type: bind
        source: ./db/postgres
        target: /var/lib/postgresql/data

