# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-02 20:08
from __future__ import unicode_literals

from django.db import migrations, models
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='abstract',
            field=models.TextField(default='El FLISoL es el evento de difusión de Software Libre más grande en Latinoamérica y está dirigido a todo tipo de público: estudiantes, académicos, empresarios, trabajadores, funcionarios públicos, entusiastas y aun personas que no poseen mucho conocimiento informático', help_text='Short idea of the event (One or two sentences)', max_length=140, verbose_name='Abstract'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('image', '700x450', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text='The image must be 700x450 px. You can crop it here.', hide_image_field=False, size_warning=True, verbose_name='Cropping'),
        ),
        migrations.AddField(
            model_name='event',
            name='image',
            field=image_cropping.fields.ImageCropField(blank=True, null=True, upload_to='images_thumbnails', verbose_name='Image'),
        ),
    ]
