# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-21 03:20
from __future__ import unicode_literals

from django.db import migrations, models
import manager.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_auto_20180316_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the event', unique=True, verbose_name='UID'),
        ),
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.CharField(help_text='For example: flisol-caba', max_length=200, validators=[manager.models.validate_url], verbose_name='URL'),
        ),
    ]
