# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-23 21:28
from __future__ import unicode_literals

from django.db import migrations, models
import manager.models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_auto_20180323_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Event Name'),
        ),
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.CharField(help_text='For example: flisol-caba', max_length=20, validators=[manager.models.validate_url], verbose_name='URL'),
        ),
    ]
