# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-18 21:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_auto_20170316_2014'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendeeAttendanceDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, help_text='The date of the attendance', verbose_name='Date')),
            ],
        ),
        migrations.CreateModel(
            name='EventUserAttendanceDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, help_text='The date of the attendance', verbose_name='Date')),
            ],
        ),
        migrations.RemoveField(
            model_name='attendee',
            name='attendance_date',
        ),
        migrations.RemoveField(
            model_name='attendee',
            name='attended',
        ),
        migrations.RemoveField(
            model_name='eventuser',
            name='attended',
        ),
        migrations.AddField(
            model_name='eventuserattendancedate',
            name='event_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.EventUser', verbose_name=b'Event User'),
        ),
        migrations.AddField(
            model_name='attendeeattendancedate',
            name='attendee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Attendee', verbose_name=b'Attendee'),
        ),
    ]
