# Generated by Django 1.11.6 on 2018-03-27 23:34

from django.db import migrations
from django.db import models

import manager.models


class Migration(migrations.Migration):
    dependencies = [
        ("manager", "0004_auto_20180323_2128"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="code",
            field=models.CharField(
                default=manager.models.generate_ticket_code,
                editable=False,
                help_text="Unique identifier for the ticket",
                max_length=21,
                unique=True,
                verbose_name="number",
            ),
        ),
    ]
