# Generated by Django 1.11.6 on 2018-03-28 04:49

import uuid

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("manager", "0005_ticket_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="registration_code",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="Code validator for in-place event self-registration",
                unique=True,
                verbose_name="code",
            ),
        ),
    ]
