# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-28 04:49
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_ticket_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='registration_code',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Code validator for in-place event self-registration', unique=True, verbose_name='code'),
        ),
    ]
