# Generated by Django 1.11.6 on 2018-04-12 04:44

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("manager", "0007_auto_20180411_0205"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[("1", "Talk"), ("2", "Workshop"), ("3", "Lightning talk"), ("4", "Other")],
                max_length=200,
                null=True,
                verbose_name="Type",
            ),
        ),
    ]
