# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-13 04:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0008_auto_20180412_0444'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendeeattendancedate',
            name='mode',
            field=models.CharField(blank=True, choices=[('1', 'Qr autoregistration'), ('2', 'Qr ticket'), ('3', 'Previous registration'), ('4', 'unregistred')], help_text='Attendance mode', max_length=200, null=True, verbose_name='Mode'),
        ),
        migrations.AddField(
            model_name='eventuserattendancedate',
            name='mode',
            field=models.CharField(blank=True, choices=[('1', 'Qr autoregistration'), ('2', 'Qr ticket'), ('3', 'Previous registration'), ('4', 'unregistred')], help_text='Attendance mode', max_length=200, null=True, verbose_name='Mode'),
        ),
    ]
