# Generated by Django 1.11.6 on 2018-04-18 04:44

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("manager", "0009_auto_20180413_0420"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="justification",
            field=models.TextField(
                blank=True,
                help_text="Why do you reject this proposal?",
                null=True,
                verbose_name="Justification",
            ),
        ),
    ]
