# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-21 04:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0010_activity_justification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Title'),
        ),
    ]
