# Generated by Django 1.11.6 on 2018-04-21 04:53

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("manager", "0010_activity_justification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="title",
            field=models.CharField(max_length=100, verbose_name="Title"),
        ),
    ]
