# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-29 15:08
from __future__ import unicode_literals

from django.db import migrations, models
import manager.models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0011_auto_20180421_0453'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='cname',
            field=models.CharField(blank=True, help_text='For example: flisol-caba', max_length=50, null=True, validators=[manager.models.validate_url], verbose_name='CNAME'),
        ),
    ]
