# Generated by Django 1.11.6 on 2018-04-30 19:04

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("manager", "0013_auto_20180430_1845"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="is_flisol",
            field=models.BooleanField(default=False, verbose_name="Is FLISoL"),
        ),
        migrations.AddField(
            model_name="event",
            name="use_schedule",
            field=models.BooleanField(default=True, verbose_name="Use Schedule"),
        ),
    ]
