# Generated by Django 1.11.6 on 2018-06-30 22:39

from django.db import migrations
from django.db import models

from manager.utils.slug import get_unique_slug


def set_slug_defaults(apps, schema_editor):
    Event = apps.get_model("manager", "Event")
    qs = Event.objects.filter(event_slug=None)
    for event in qs:
        event.event_slug = get_unique_slug(event, "slug", "event_slug")
        event.save()


class Migration(migrations.Migration):
    dependencies = [
        ("manager", "0015_auto_20180630_2158"),
    ]

    operations = [
        # create the field as nullable
        migrations.AddField(
            model_name="event",
            name="event_slug",
            field=models.SlugField(
                help_text="For example: flisol-caba",
                max_length=100,
                unique=True,
                verbose_name="URL",
                null=True,
            ),
        ),
        # set the default for existents events.
        migrations.RunPython(set_slug_defaults),
        # set the fiels as not nullable.
        migrations.AlterField(
            model_name="event",
            name="event_slug",
            field=models.SlugField(
                help_text="For example: flisol-caba",
                max_length=100,
                unique=True,
                verbose_name="URL",
            ),
            preserve_default=False,
        ),
    ]
