# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-20 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0014_auto_20180430_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='num_vote_down',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='activity',
            name='num_vote_up',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='activity',
            name='vote_score',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='activity',
            name='additional_info',
            field=models.TextField(blank=True, help_text='Any info you consider relevant                                                    for the organizer: i.e. Write here                                                    if your activity has any special requirement', null=True, verbose_name='Additional Info'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='is_dummy',
            field=models.BooleanField(default=False, help_text='A dummy activity is used for example for coffee                                                breaks. We use this to exclude it from the index                                                page and other places', verbose_name='Is a dummy Activity?'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='labels',
            field=models.CharField(help_text='Comma separated tags. i.e. Linux,                                           Free Software, Archlinux', max_length=200, verbose_name='Labels'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='presentation',
            field=models.FileField(blank=True, help_text='Any material you are going to use                                                 for the talk (optional, but recommended)', null=True, upload_to='talks', verbose_name='Presentation'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='speaker_contact',
            field=models.EmailField(help_text='Where can whe reach you                                                     from the organization team?', max_length=254, verbose_name='Speaker Contact'),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='additional_info',
            field=models.CharField(blank=True, help_text='Any additional info you consider                                                    relevant for the organizers', max_length=200, null=True, verbose_name='Additional Info'),
        ),
        migrations.AlterField(
            model_name='collaborator',
            name='assignation',
            field=models.CharField(blank=True, help_text='Anything you can help with                                                (i.e. Talks, Coffee...)', max_length=200, null=True, verbose_name='Assignation'),
        ),
        migrations.AlterField(
            model_name='collaborator',
            name='time_availability',
            field=models.CharField(blank=True, help_text='Time gap in which you can                                                      help during the event. i.e.                                                      "All the event", "Morning",                                                      "Afternoon", ...', max_length=200, null=True, verbose_name='Time Availability'),
        ),
        migrations.AlterField(
            model_name='installation',
            name='notes',
            field=models.TextField(blank=True, help_text='Any information or trouble you found                                          and consider relevant to document', null=True, verbose_name='Notes'),
        ),
    ]
