# Generated by Django 1.11.6 on 2018-07-01 16:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("manager", "0016_event_event_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="event",
            name="uid",
        ),
    ]
