# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-01 23:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0017_auto_20180701_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='num_vote_down',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='activity',
            name='num_vote_up',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='activity',
            name='vote_score',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
