# Generated by Django 1.11.6 on 2018-07-30 02:11

import django.db.models.deletion
from django.conf import settings
from django.contrib.auth.hashers import make_password
from django.core.exceptions import MultipleObjectsReturned
from django.db import migrations
from django.db import models
from django.utils.crypto import get_random_string


def set_owner_defaults(apps, schema_editor):
    Activity = apps.get_model("manager", "Activity")
    EventUser = apps.get_model("manager", "EventUser")
    User = apps.get_model(settings.AUTH_USER_MODEL)
    qs = Activity.objects.filter(owner=None)

    for activity in qs:
        email = activity.speaker_contact
        username = "{}-{}".format(email.split("@")[0], get_random_string(4))
        password = make_password(None)
        defaults = {"username": username, "password": password}
        try:
            user, created = User.objects.get_or_create(email=email, defaults=defaults)
            if created:
                print(f"new user created: {user.email}, (activity: {activity.title})")
        except MultipleObjectsReturned:
            print(f"Multiple EventUser returned: {user}, (activity: {activity.title})")
            user = User.objects.filter(email=email).first()
        # get a EventUser
        try:
            event_user, created = EventUser.objects.get_or_create(
                user=user, defaults={"event": activity.event}
            )
            if created:
                print(f"new EventUser created: {event_user}, (activity: {activity.title})")
        except MultipleObjectsReturned:
            print(f"Multiple EventUser returned: {user}, (activity: {activity.title})")
            event_user = EventUser.objects.filter(user=user).first()
        activity.owner = event_user
        activity.save()


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("manager", "0018_auto_20180701_2305"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="owner",
            field=models.ForeignKey(
                help_text="Speaker or the person in charge of the activity",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="manager.EventUser",
            ),
        ),
        migrations.AlterField(
            model_name="activity",
            name="speaker_contact",
            field=models.EmailField(
                blank=True,
                help_text="Where can whe reach you                                                     from the organization team?",
                max_length=254,
                null=True,
                verbose_name="Speaker Contact",
            ),
        ),
        migrations.RunPython(set_owner_defaults),
        migrations.AlterField(
            model_name="activity",
            name="owner",
            field=models.ForeignKey(
                help_text="Speaker or the person in charge of the activity",
                on_delete=django.db.models.deletion.CASCADE,
                to="manager.EventUser",
            ),
        ),
    ]
