# Generated by Django 1.11.6 on 2018-08-12 20:56

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("manager", "0018_auto_20180701_2305"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="registration_closed",
            field=models.BooleanField(
                default=False, help_text="set it to True to force the registration to be closed"
            ),
        ),
    ]
