# Generated by Django 1.11.6 on 2018-07-30 03:00

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("manager", "0019_auto_20180730_0211"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="activity",
            name="speaker_contact",
        ),
        migrations.AddField(
            model_name="activity",
            name="speaker_bio",
            field=models.TextField(
                blank=True,
                help_text='Tell us about you (we will user it as your "bio" in our website',
                null=True,
                verbose_name="Speaker Bio",
            ),
        ),
    ]
