# Generated by Django 1.11.6 on 2018-08-12 22:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("manager", "0020_auto_20180730_0300"),
        ("manager", "0019_event_registration_closed"),
    ]

    operations = []
