# Generated by Django 1.11.6 on 2018-08-12 22:13

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("manager", "0021_merge_20180812_2212"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="speaker_bio",
            field=models.TextField(
                help_text='Tell us about you (we will user it as your "bio" in our website',
                null=True,
                verbose_name="Speaker Bio",
            ),
        ),
    ]
