# Generated by Django 1.11.6 on 2018-08-12 22:39

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("manager", "0022_auto_20180812_2213"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="activities_proposal_form_text",
            field=models.TextField(
                blank=True, help_text="A message to show in the activities proposal form", null=True
            ),
        ),
    ]
