# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-12 22:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0022_auto_20180812_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='activities_proposal_form_text',
            field=models.TextField(blank=True, help_text='A message to show in the activities proposal form', null=True),
        ),
    ]
