# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-12 23:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def set_activity_type(apps, schema_editor):

    activity_type_choices = {
        '1': 'Talk',
        '2': 'Workshop',
        '3': 'Lightning talk',
        '4': 'Other',
    }
    Activity = apps.get_model('manager', 'Activity')
    ActivityType = apps.get_model('manager', 'ActivityType')
    qs = Activity.objects.filter(activity_type=None)

    for activity_type in activity_type_choices.values():
        at = ActivityType.objects.create(name=activity_type)
        print("new activity_type created {}".format(at.name))

    for activity in qs:
        activity.activity_type = ActivityType.objects.get(
            name=activity_type_choices.get(activity.type, 'Talk'))
        activity.save()


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0023_event_activities_proposal_form_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Kind of activity', max_length=60)),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='activity_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.ActivityType'),
        ),
        migrations.RunPython(set_activity_type),
    ]
