# Generated by Django 1.11.6 on 2018-08-13 00:10

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("manager", "0024_auto_20180812_2349"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="activity",
            name="type",
        ),
        migrations.AlterField(
            model_name="activity",
            name="activity_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="manager.ActivityType"
            ),
        ),
    ]
