# Generated by Django 1.11.6 on 2018-08-13 00:32

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("manager", "0025_auto_20180813_0010"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventtag",
            name="background",
            field=models.ImageField(
                blank=True,
                help_text="A image to show in the background of",
                null=True,
                upload_to="",
            ),
        ),
        migrations.AlterField(
            model_name="eventtag",
            name="message",
            field=models.TextField(
                blank=True,
                help_text="A message to show in the center of the page",
                max_length=280,
                null=True,
            ),
        ),
    ]
