# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-13 00:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0026_auto_20180813_0032'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventolSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background', models.ImageField(blank=True, help_text='A image to show in the background of', null=True, upload_to='')),
                ('logo_header', models.ImageField(blank=True, help_text='This logo will be showed in the corner right of the page', null=True, upload_to='')),
                ('logo_landing', models.ImageField(blank=True, help_text='Logo to show in the center of the page', null=True, upload_to='')),
                ('message', models.TextField(blank=True, help_text='A message to show in the center of the page', max_length=280, null=True)),
            ],
            options={
                'verbose_name_plural': 'Eventol settings',
                'verbose_name': 'Eventol setting',
            },
        ),
    ]
