# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-19 20:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0027_eventolsetting'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['title'], 'permissions': (('can_review_activity', 'Can review Activities'),), 'verbose_name': 'Activity', 'verbose_name_plural': 'Activities'},
        ),
    ]
