# Generated by Django 1.11.6 on 2018-09-30 19:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("manager", "0030_attendee_customfields"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="customfield",
            unique_together={("form", "slug")},
        ),
    ]
