# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-07 03:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0031_auto_20180930_1950'),
        ('manager', '0029_auto_20181005_0503'),
    ]

    operations = [
    ]
