# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-12 06:40
from __future__ import unicode_literals

# import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0032_merge_20181007_0309'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventolsetting',
            options={'verbose_name': 'eventoL setting', 'verbose_name_plural': 'eventoL settings'},
        ),
        migrations.AlterField(
            model_name='activity',
            name='additional_info',
            field=models.TextField(blank=True, help_text='Info you consider relevant                                                    to the organizer, special                                                    activity requirements, etc.', null=True, verbose_name='Additional Info'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='labels',
            field=models.CharField(help_text='Comma separated tags. i.e. Linux,                                           Free Software, Devuan', max_length=200, verbose_name='Labels'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='presentation',
            field=models.FileField(blank=True, help_text='Material you are going to use                                                 for the talk (optional, but recommended)', null=True, upload_to='talks', verbose_name='Presentation'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='speakers_names',
            field=models.CharField(help_text='Comma separated speaker names', max_length=600, verbose_name='Speakers Names'),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='additional_info',
            field=models.CharField(blank=True, help_text='Additional info you consider                                                    relevant to the organizers', max_length=200, null=True, verbose_name='Additional Info'),
        ),
        migrations.AlterField(
            model_name='collaborator',
            name='additional_info',
            field=models.CharField(blank=True, help_text='Additional info you consider relevant', max_length=200, null=True, verbose_name='Additional Info'),
        ),
        migrations.AlterField(
            model_name='collaborator',
            name='assignation',
            field=models.CharField(blank=True, help_text='Anything you can help with                                                (i.e. Talks, Coffee…)', max_length=200, null=True, verbose_name='Assignation'),
        ),
        migrations.AlterField(
            model_name='collaborator',
            name='time_availability',
            field=models.CharField(blank=True, help_text='Time period in which you can                                                      help during the event. i.e.                                                      "All the event", "Morning",                                                      "Afternoon", …', max_length=200, null=True, verbose_name='Time Availability'),
        ),
        migrations.AlterField(
            model_name='event',
            name='abstract',
            field=models.TextField(help_text='Idea of the event                                             (one or two sentences)', max_length=250, verbose_name='Abstract'),
        ),
        migrations.AlterField(
            model_name='event',
            name='css_custom',
            field=models.FileField(blank=True, help_text='Custom CSS file for event page', null=True, upload_to='custom_css', verbose_name='Custom css'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_information',
            field=models.TextField(blank=True, help_text='Event Info HTML', null=True, verbose_name='Event Info'),
        ),
        migrations.AlterField(
            model_name='event',
            name='template',
            field=models.FileField(blank=True, help_text='Custom template HTML for event index page', null=True, upload_to='templates', verbose_name='Template'),
        ),
        migrations.AlterField(
            model_name='eventolsetting',
            name='logo_header',
            field=models.ImageField(blank=True, help_text='This logo will be shown in the right corner of the page', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='eventtag',
            name='logo_header',
            field=models.ImageField(blank=True, help_text='This logo will be shown in the right corner of the page', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='installation',
            name='notes',
            field=models.TextField(blank=True, help_text='Info or trouble you                                          consider relevant to document', null=True, verbose_name='Notes'),
        ),
    ]
