# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-13 16:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0033_auto_20191012_0640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='limit_proposal_date',
            field=models.DateField(default=datetime.date.today, help_text='Limit date to submit talk proposals', verbose_name='Limit Proposals Date'),
        ),
    ]
