# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-16 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0036_auto_20191015_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='use_talks',
            field=models.BooleanField(default=True, verbose_name='Use Talks'),
        ),
    ]
