# Generated by Django 1.11.23 on 2019-10-16 16:39

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("manager", "0037_event_use_talks"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                help_text="Select tags to show this event in the EventTag landing",
                to="manager.EventTag",
            ),
        ),
    ]
