# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-22 15:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0038_auto_20191016_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.ActivityType', verbose_name='Activity Type'),
        ),
    ]
