# Generated by Django 1.11.23 on 2019-10-22 15:01

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("manager", "0038_auto_20191016_1639"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="activity_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="manager.ActivityType",
                verbose_name="Activity Type",
            ),
        ),
    ]
