# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-24 15:36
from __future__ import unicode_literals

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0039_auto_20191022_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('image', '700x450', adapt_rotation=False, allow_fullsize=False, free_crop=True, help_text='The image must be 700x450 px. You can crop it here.', hide_image_field=False, size_warning=True, verbose_name='Cropping'),
        ),
    ]
