# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-01-15 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0041_add_unaccent_extension'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendeeattendancedate',
            name='mode',
            field=models.CharField(blank=True, choices=[('1', 'Qr autoregistration'), ('2', 'Qr ticket'), ('3', 'Previous registration'), ('4', 'unregistred')], help_text='Attendance mode', max_length=200, null=True, verbose_name='Mode'),
        ),
        migrations.AlterField(
            model_name='eventuserattendancedate',
            name='mode',
            field=models.CharField(blank=True, choices=[('1', 'Qr autoregistration'), ('2', 'Qr ticket'), ('3', 'Previous registration'), ('4', 'unregistred')], help_text='Attendance mode', max_length=200, null=True, verbose_name='Mode'),
        ),
    ]
