# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-22 02:55
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0044_auto_20200115_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='activities_proposal_form_text',
            field=ckeditor.fields.RichTextField(blank=True, help_text='A message to show in the activities proposal form', null=True, verbose_name='Activity proposal form text'),
        ),
    ]
