# Generated by Django 1.11.29 on 2021-08-13 17:43

from django.contrib.auth.models import Group
from django.contrib.auth.models import Permission
from django.db import migrations

from manager.constants import ORGANIZER_GROUP_NAME
from manager.constants import ORGANIZER_PERMISSION_CODE_NAMES
from manager.security import create_organizers_group


def update_organizers_permissions(apps, schema_editor):
    group = Group.objects.filter(name__iexact=ORGANIZER_GROUP_NAME).first()
    if group is None:
        group = create_organizers_group()
    for permission_codename in ORGANIZER_PERMISSION_CODE_NAMES:
        permissions = Permission.objects.filter(
            codename=permission_codename, content_type__app_label="manager"
        )
        for permission in permissions.iterator():
            group.permissions.add(permission)
    group.save()


class Migration(migrations.Migration):
    dependencies = [
        ("manager", "0045_activities_proposal_form_text_to_rich_text"),
    ]

    operations = [migrations.RunPython(update_organizers_permissions)]
