# Generated by Django 1.11.29 on 2023-03-12 14:24

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("manager", "0046_update_organizers_permissions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="place",
            field=models.TextField(blank=True, null=True, verbose_name="Place"),
        ),
    ]
