# Generated by Django 3.2 on 2024-06-22 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0047_remove_place_from_required_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customform',
            name='sites',
        ),
        migrations.RemoveField(
            model_name='event',
            name='customForm',
        ),
        migrations.DeleteModel(
            name='CustomField',
        ),
        migrations.DeleteModel(
            name='CustomForm',
        ),
    ]
