# Generated by Django 4.2 on 2024-06-22 17:35

from django.db import migrations
import django_jsonfield_backport.models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0048_auto_20240622_0351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='customFields',
            field=django_jsonfield_backport.models.JSONField(default=dict),
        ),
    ]
