# Generated by Django 4.2 on 2025-03-23 15:58

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0050_alter_attendee_customfields'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Geom'),
        ),
    ]
