# Generated by Django 4.2 on 2025-03-24 03:19

import json

from django.db import migrations
from django.contrib.gis.geos import Point


def migrate_place_to_geom(apps, schema_editor):
    Event = apps.get_model('manager', 'Event')
    for event in Event.objects.all():
        if event.place:
            try:
                place_data = json.loads(event.place)
                lng = place_data['geometry']['location']['lng']
                lat = place_data['geometry']['location']['lat']

                event.geom = Point(lng, lat)
                event.save()
            except Exception:
                pass


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0051_event_geom'),
    ]

    operations = [
        migrations.RunPython(migrate_place_to_geom)
    ]
