# Generated by Django 4.2 on 2025-03-24 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0051_alter_event_activities_proposal_form_text_and_more'),
        ('manager', '0052_move_place_to_geom'),
    ]

    operations = [
    ]
