# Generated by Django 4.2 on 2025-04-16 22:12

from django.db import migrations, models
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0053_merge_20250324_0534'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='allow_contact_or_subscription',
            field=models.BooleanField(default=False, help_text='Allow the use of contact data for event updates or subscriptions', verbose_name='Allow Contact or Subscription'),
        ),
        migrations.AddField(
            model_name='event',
            name='show_contact_by_email',
            field=models.BooleanField(default=True, help_text='Show the contact email to the organization in the navigation bar', verbose_name='Show contact email'),
        ),
        migrations.AddField(
            model_name='eventuser',
            name='allow_contact_or_subscription',
            field=models.BooleanField(default=False, help_text='Allow the use of contact data for event updates or subscriptions', verbose_name='Allow Contact or Subscription'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='image',
            field=image_cropping.fields.ImageCropField(blank=True, help_text='This image will represent the activity and will be displayed for represent it', null=True, upload_to='images_thumbnails', verbose_name='Image'),
        ),
    ]
