# Generated by Django 4.2 on 2025-04-21 19:05

from django.conf import settings
from django.db import connection
from django.db import migrations


def init_spatial_metadata(apps, schema_editor):
    is_dev = getattr(settings, 'DEBUG', False)
    is_spatialite = connection.settings_dict.get('ENGINE') == 'django.contrib.gis.db.backends.spatialite'

    if is_dev and is_spatialite:
        try:
            with connection.cursor() as cursor:
                cursor.execute("SELECT InitSpatialMetaData(1);")
        except Exception:
            pass


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0054_attendee_allow_contact_or_subscription_and_more'),
    ]

    operations = [
        migrations.RunPython(init_spatial_metadata, reverse_code=migrations.RunPython.noop),
    ]
