# Generated by Django 4.2 on 2025-04-21 19:09

from django.db import migrations


def re_save_all_events(apps, schema_editor):
    Event = apps.get_model('manager', 'Event')

    for event in Event.objects.all():
        event.save()


class Migration(migrations.Migration):
    dependencies = [
        ('manager', '0055_init_spatialite'),
    ]

    operations = [
        migrations.RunPython(re_save_all_events, reverse_code=migrations.RunPython.noop),
    ]
