# Generated by Django 4.2 on 2025-04-23 12:41

from django.db import migrations


def re_save_all_activities(apps, schema_editor):
    Activity = apps.get_model('manager', 'Activity')

    for activity in Activity.objects.all():
        activity.save()


class Migration(migrations.Migration):
    dependencies = [
        ('manager', '0056_update_cropping'),
    ]

    operations = [
        migrations.RunPython(re_save_all_activities, reverse_code=migrations.RunPython.noop),
    ]
