parser: babel-eslint
extends:
 - airbnb
 - plugin:import/errors
 - plugin:import/warnings
env:
 browser: true
 node: true
plugins:
 - import
globals:
 gettext: true
 $: true
 L: true
 module: true
 process: true
 __dirname: true
 global: true
 window: true
 document: true
 console: true
parserOptions:
 ecmaVersion: 6
 sourceType: module
 ecmaFeatures:
  jsx: true
  modules: true
  experimentalObjectRestSpread: true
settings:
 react:
   pragma: React
   version: 16.4
 import/resolver:
   node:
     paths: ['src/']
     extensions:
      - .js
      - .jsx
rules:
  arrow-parens: [error, as-needed]
  camelcase: [error, {ignoreDestructuring: true, allow: [^UNSAFE_, first_name, last_name, render_components, ws_protocol]}]
  jsx-a11y/anchor-is-valid: off
  jsx-quotes: [error, prefer-single]
  no-prototype-builtins: off
  object-curly-spacing: [error, never]  
  space-before-blocks: [error, {functions: never, keywords: never, classes: always}]
  space-before-function-paren: [error, {anonymous: always, named: never, asyncArrow: always}]
overrides:
  files:
    - '**/jest/*.{js,jsx}'
    - "**/*.{spec,test}.{js,jsx}"
  env:
    jest: true
  plugins:
    - jest
  globals:
    global: true
    jest: true
  rules:
    import/first: off
    jest/no-disabled-tests: warn
    jest/no-focused-tests: error
    jest/no-identical-title: error
    jest/prefer-to-have-length: warn
    jest/valid-expect: error
    one-var: off
    one-var-declaration-per-line: off
